### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by Obi-nwanne** [Flutterwave/Vue#15]
this dependency was not found:
* flutterwave-vue-v3 in ./src/main.ts
To install it, you can run: npm install --save flutterwave-vue-v3

v 1.0.8

**Comment by toybz** [comment]
Hello @Obi-nwanne 
Please share more details on this issue with us.

Please state your Vue version number,
Is your app using Typescript and the version of the Flw-Vue-Package to enable us investigate and resolve this

**Comment by vinosamari** [comment]
@toybz I'm facing the same issue with Nuxt 2.15.8 and the flutterwave-vue-v3 package. I've reinstalled it to no avail. Please help!

**Comment by Obi-nwanne** [comment]
@toybz 
vue version is ^2.6.11" and typescript
"flutterwave-vue-v3": "~1.0.8"
i had to revert to "flutterwave-vue-v3": "1.0.5" before it worked

**Comment by toybz** [comment]
Sincere apologies for this issue and the late response.
We have investigated and fixed the issue, the update will be live very soon today.
I will be closing this issue now.

Thank you for raising this and for your understanding.
