### ISSUE TITLE
Test mode no longer accepts different currencies

### ISSUE THREAD

**Issue by vinosamari** [Flutterwave/Vue#20]
Hello, 
Putting my account in test mode no longer allows testing with currencies other than the one for the account. e.g If my account is NGN I cannot test with a USD (or any other currency) transaction which wasn't the case until recently. The simulation of transactions is essential for demos for potential clients.

**Comment by toybz** [comment]
Hello @vinosamari 

To resolve this issue, please send an email to developer@flutterwavego.com,
requesting for International collections to be enabled on your (test) account.

I will be closing this issue here because it is not related to the SDK.
