### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by su-zm** [Flutterwave/Vue#5]
Howdy,

Thank you so much for this awesome library :fire: 

I just encountered the following error while testing out the library in a browser:

```
Access to fetch at 'https://kgelfdz7mf.execute-api.us-east-1.amazonaws.com/staging/sendevent' 
from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'
header is present on the requested resource. If an opaque response serves your needs,
set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
I'm using [quasar](https://quasar.dev) and I intend to target Android.

Would be most grateful for help on resolving this.

**Comment by toybz** [comment]
Hello @su-zm 

Thank  you for raising this and apologies for the late response.

You can ignore this issue as it has no effect on the Lib or your app performance.
We will also update  the SDK to not call this URL when in dev environment in future update.

Best regards
