### ISSUE TITLE
Dealing with timeouts and prolonged payment procesing

### ISSUE THREAD

**Issue by engineervix** [Flutterwave/Vue#7]
First of all, I'd like to thank you for putting up this excellent library, it really makes it much easier and faster to integrate flutterwave payments into a vue.js application.

I have noticed situations where, after payment has been initiated, flutterwave takes a long time to finalize the payment. The money would already have been deducted from one's account, but the payment would still be incomplete on the app, and therefore, a redirect or callback function would still be pending.

When a user gets tired of waiting and clicks the modal close button, they are prompted to confirm whether they want to cancel the transaction. Upon confirmation, the modal is closed and the payment processing is cancelled. However, money has already been deducted from one's account (they even receive a receipt and flutterwave records it as a successful transaction), and yet they cannot use the service because payment wasn't "successful" on the app (in the sense that neither `redirect_url` nor `callback` were triggered). 

I would therefore like to request that such matters are looked into and addressed, so that users have a better user experience. It would be good if people could get a refund automatically if a transaction wasn't successful.

Thanks.

**Comment by vinosamari** [comment]
I've also been scouring the docs to see how to handle situations like this seeing as the modal logic can also fail with no way of letting the app know. No luck yet.

**Comment by Corvus97** [comment]
Hello @engineervix @vinosamari ,

Thanks for sharing this feedback with the team. The team is working on this critical feedback. We would notify you as soon as this is resolved.

In the interim, you can get more updates from the Engineering team on our [Slack](https://bit.ly/34Vkzcg).
